version: "3"
services:
    db:
      image: postgres:alpine
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5432:5432'
      volumes: 
        - ./db:/var/lib/postgresql/data
        - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local